### ISSUE TITLE
Search for `poetry` envs in `~/.cache/pypoetry/virtualenvs`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-environment-tools#150] opened 2024-09-19 00:08 UTC
These seems to be common locations:
- `~/.cache/pypoetry/virtualenvs`
- `~/.cache/pypoetry/`
- `~/.config/pypoetry/virtualenvs`
- `~/.config/pypoetry`

**Comment by DonJayamanne** [comment] 2024-10-01 05:05
Based on the current algorithm, we shouldn't have to hard code these.
Can you share more information on where the current algorithm isn't working, e.g. steps to repro or the like.
Or logs.

**Comment by karthiknadig** [comment] 2024-10-01 05:15
Those environments are where poetry is adding the environments when you use a devcontainer. The issues on native locator that were filed all complained that the environments in that location were not found.

**Comment by DonJayamanne** [comment] 2024-10-01 05:32
Link to one of the issues https://github.com/microsoft/vscode-python/issues/24071

**Comment by karthiknadig** [comment] 2024-10-03 05:42
https://github.com/microsoft/vscode-python/issues/24133

**Comment by DonJayamanne** [comment] 2024-10-31 02:07
Duplicate of https://github.com/microsoft/python-environment-tools/issues/161

**Closed by DonJayamanne** 2024-10-31 02:07 UTC
